### ISSUE TITLE
pathOpt struct external usage

### ISSUE THREAD

**Issue by BoardzMaster** [landlock-lsm/go-landlock#11]
Dear Günther!
Is it possible to make pathOpt structure for external usage cause it would be convenient in **runc/containerd** implementation?
![image](https://user-images.githubusercontent.com/8223920/130604373-1d8dc27a-37ab-4f41-8ae0-000ed5922ef0.png)

It could be easily parsed from runc spec  .json and into **opts** array directly and then fed to RestrictPaths(**opts** ...pathOpt) function

**Comment by gnoack** [comment]
Hello Konstantin!

We can expose the type itself if that helps (make `PathOpts` uppercase), but the internals are hidden on purpose here, so that it can be used if `RestrictPaths()` will need special additional options other than the existing ones in the future.

Would that help?

**Comment by BoardzMaster** [comment]
Yes, we can of course.  But if we want to use go-landlock lib so maybe it would be more suitable tha all changes come from outside and we could keep the library consistent.  What do you think?

**Comment by gnoack** [comment]
I have trouble understanding your comment. Obviously, you shouldn't need to maintain your own copy of go-landlock because of this. I'm happy to make the necessary changes here to support your use case, as long as I understand what these necessary changes are, and as long as it's done in a way that doesn't complicate things in the future.

If it's just about making the `pathOpt` type public, we can do that. Would that work for your use case?

**Comment by BoardzMaster** [comment]
Sorry if my comment confused you! If it's possible please could you make pathOpt public?  In runc implementation, I would parse Landlock rules (from spec config.json file) into an array of pathOpt and feed it to RestrictPaths() function. 
Cause as I understand RestrictPaths() function could be used just with predefined RODirs....RWFiles  pathopts or with PathAccess() function.

**Comment by gnoack** [comment]
Sounds good, I made the `pathOpt` type public. I'll close the bug for now, assuming that this works for your use case. If there are more API usage issues with `pathOpt` that I have overlooked, please feel free to reopen.

**Comment by BoardzMaster** [comment]
Thank you so much!!!!
