### ISSUE TITLE
Deal with the case where the kernel supports a higher Landlock version than known to go-landlock

### ISSUE THREAD

**Issue by gnoack** [landlock-lsm/go-landlock#13]
Deal with the case where the kernel supports a higher Landlock version than known to go-landlock.

**Comment by gnoack** [comment]
Addressed in https://github.com/landlock-lsm/go-landlock/commit/4e4877f69930828348e10f975c3c778cca318bf6

Constructing a `Config` with unknown HandledAccessFS flag values is made impossible in the constructor for the `Config` struct, and so it's more naturally clear that users need to upgrade go-landlock in order to use Landlock features that belong to higher Landlock ABI versions.

**Comment by l0kod** [comment]
Note about `MustConfig`: https://github.com/landlock-lsm/go-landlock/commit/4e4877f69930828348e10f975c3c778cca318bf6#r55652317

**Comment by gnoack** [comment]
Thanks, I appreciate the review (answered to the comment inline).

I have thought a bit about how this API can evolve when Landlock supports non-filesystem restrictions at some point. I think this is reasonable to do without surprising users. I'll try to write it up (tracking in #16) and run it by you.
