### ISSUE TITLE
Prepare for Landlock V2

### ISSUE THREAD

**Issue by gnoack** [landlock-lsm/go-landlock#20]
Landlock V2 is scheduled to appear in kernel 5.19 ([mail with links to the patches](https://lore.kernel.org/all/20220523161245.2451265-1-mic@digikod.net/)) - let's get support into Go-Landlock for it.

**Comment by gnoack** [comment]
Final patch set so far: https://lore.kernel.org/all/20220506161102.525323-1-mic@digikod.net/

**Comment by l0kod** [comment]
Right, it has been merged here: https://git.kernel.org/torvalds/c/cb44e4f061e16be65b8a16505e121490c66d30d0
I'll Cc you next time :wink: 
Thanks!
