### ISSUE TITLE
Auto-generated documentation

### ISSUE THREAD

**Issue by l0kod** [landlock-lsm/go-landlock#24]
As for https://github.com/landlock-lsm/rust-landlock/pull/13, I think it would be nice to update the API documentation as soon as it get merged.

I guess we could use https://code.rocketnine.space/tslocum/godoc-static

**Comment by gnoack** [comment]
For Go, the Go team maintains a service which renders and caches the documentation for all open source packages at https://pkg.go.dev/github.com/landlock-lsm/go-landlock/landlock. It gets automatically updated and is used pretty consistently in the Go community. This is what I'm also linking to in the readme file.

So unless you want to host the documentation on a separate domain somewhere, I think we should be fine as is? (Please reopen if you think this is not sufficient)
